// Copyright (C) 2022  Aranggi J. Toar <at@aranggitoar.com>
// Full GPL-2.0 notice  https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

// Array of correct Bible book name order.
// The format of the names are taken from the sources.
export const correctlyOrderedBibleBookNameReference = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  'Ruth',
  'I Samuel',
  'II Samuel',
  'I Kings',
  'II Kings',
  'I Chronicles',
  'II Chronicles',
  'Ezra',
  'Nehemiah',
  'Esther',
  'Job',
  'Psalms',
  'Proverbs',
  'Ecclesiastes',
  'Song of Solomon',
  'Isaiah',
  'Jeremiah',
  'Lamentations',
  'Ezekiel',
  'Daniel',
  'Hosea',
  'Joel',
  'Amos',
  'Obadiah',
  'Jonah',
  'Micah',
  'Nahum',
  'Habakkuk',
  'Zephaniah',
  'Haggai',
  'Zechariah',
  'Malachi',
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  '1 Thessalonians',
  '2 Thessalonians',
  '1 Timothy',
  '2 Timothy',
  'Titus',
  'Philemon',
  'Hebrew',
  'James',
  '1 Peter',
  '2 Peter',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Revelation',
];

export const correctlyOrderedBibleBookNameReferenceID = [
  'Kejadian',
  'Keluaran',
  'Imamat',
  'Bilangan',
  'Ulangan',
  'Yosua',
  'Hakim-hakim',
  'Rut',
  'I Samuel',
  'II Samuel',
  'I Raja-raja',
  'II Raja-raja',
  'I Tawarikh',
  'II Tawarikh',
  'Ezra',
  'Nehemia',
  'Ester',
  'Ayub',
  'Mazmur',
  'Amsal',
  'Pengkhotbah',
  'Kidung Agung',
  'Yesaya',
  'Yeremia',
  'Ratapan',
  'Yehezkiel',
  'Daniel',
  'Hosea',
  'Yoel',
  'Amos',
  'Obaja',
  'Yunus',
  'Mikha',
  'Nahum',
  'Habakuk',
  'Zefanya',
  'Hagai',
  'Zakharia',
  'Maleakhi',
  'Matius',
  'Markus',
  'Lukas',
  'Yohanes',
  'Kisah Para Rasul',
  'Roma',
  '1 Korintus',
  '2 Korintus',
  'Galatia',
  'Efesus',
  'Filipi',
  'Kolose',
  '1 Tesalonika',
  '2 Tesalonika',
  '1 Timotius',
  '2 Timotius',
  'Titus',
  'Filemon',
  'Ibrani',
  'Yakobus',
  '1 Petrus',
  '2 Petrus',
  '1 Yohanes',
  '2 Yohanes',
  '3 Yohanes',
  'Yudas',
  'Wahyu',
];

// Array of correct OT Bible book name order.
export const correctlyOrderedOTBibleBookNameReference = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  'Ruth',
  '1 Samuel',
  '2 Samuel',
  '1 Kings',
  '2 Kings',
  '1 Chronicles',
  '2 Chronicles',
  'Ezra',
  'Nehemiah',
  'Esther',
  'Job',
  'Psalms',
  'Proverbs',
  'Ecclesiastes',
  'Song of Songs',
  'Isaiah',
  'Jeremiah',
  'Lamentations',
  'Ezekiel',
  'Daniel',
  'Hosea',
  'Joel',
  'Amos',
  'Obadiah',
  'Jonah',
  'Micah',
  'Nahum',
  'Habakkuk',
  'Zephaniah',
  'Haggai',
  'Zechariah',
  'Malachi',
];

export const correctlyOrderedOTBibleBookNameReferenceID = [
  'Kejadian',
  'Keluaran',
  'Imamat',
  'Bilangan',
  'Ulangan',
  'Yosua',
  'Hakim-hakim',
  'Rut',
  'I Samuel',
  'II Samuel',
  'I Raja-raja',
  'II Raja-raja',
  'I Tawarikh',
  'II Tawarikh',
  'Ezra',
  'Nehemia',
  'Ester',
  'Ayub',
  'Mazmur',
  'Amsal',
  'Pengkhotbah',
  'Kidung Agung',
  'Yesaya',
  'Yeremia',
  'Ratapan',
  'Yehezkiel',
  'Daniel',
  'Hosea',
  'Yoel',
  'Amos',
  'Obaja',
  'Yunus',
  'Mikha',
  'Nahum',
  'Habakuk',
  'Zefanya',
  'Hagai',
  'Zakharia',
  'Maleakhi',
];

// Array of correct NT Bible book name order.
export const correctlyOrderedNTBibleBookNameReference = [
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  '1 Thessalonians',
  '2 Thessalonians',
  '1 Timothy',
  '2 Timothy',
  'Titus',
  'Philemon',
  'Hebrew',
  'James',
  '1 Peter',
  '2 Peter',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Revelation',
];

export const correctlyOrderedNTBibleBookNameReferenceID = [
  'Matius',
  'Markus',
  'Lukas',
  'Yohanes',
  'Kisah Para Rasul',
  'Roma',
  '1 Korintus',
  '2 Korintus',
  'Galatia',
  'Efesus',
  'Filipi',
  'Kolose',
  '1 Tesalonika',
  '2 Tesalonika',
  '1 Timotius',
  '2 Timotius',
  'Titus',
  'Filemon',
  'Ibrani',
  'Yakobus',
  '1 Petrus',
  '2 Petrus',
  '1 Yohanes',
  '2 Yohanes',
  '3 Yohanes',
  'Yudas',
  'Wahyu',
];
