// Copyright (C) 2022  Aranggi J. Toar <at@aranggitoar.com>
// Full GPL-2.0 notice  https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

export const byzMTMorphologicalDataMock = {
  rawData: [
    'N-PRI',
    'CONJ',
    'V-AAI-3S',
    'R-GPN',
    'V-PAP-NPM',
    'T-DPM',
    'A-NSN',
    'P-1GS',
    'PREP',
    'COND',
    'PRT',
    'N-NSF',
    'ADV',
    'T-GSM',
    'ARAM',
    'A-DPM',
    'HEB',
    'INJ',
  ],
  result: [
    'Noun',
    'Conjunction',
    'Verb',
    'Pronoun',
    'Verb',
    'Definite Article',
    'Adjective',
    'Pronoun',
    'Preposition',
    'Conditional Particle',
    'Particle',
    'Noun',
    'Adverb',
    'Definite Article',
    'Aramaic Transliteration',
    'Adjective',
    'Hebrew Transliteration',
    'Interjection',
  ],
};

export const morphHBMorphologicalDataMock = {
  rawData: [
    'HVqp3ms',
    'HTo',
    'HC/To',
    'HR',
    'HC/Vqw3mp',
    'HAampa',
    'HD',
    'HVPsfsa',
    'HAamsa',
    'HC/Ncmsc',
    'HNcfsa',
    'HTd/Ncfsa',
    'HC/Vqw3ms',
    'HC',
    'HC/C',
    'HC/R/Vpc/Sp3mp', // Found in Daniel 1:4
    'HNcmpc/Sp3fs',
    'HVNi3mp',
  ],
  result: [
    'Verb',
    'Particle',
    'Particle',
    'Preposition',
    'Verb',
    'Adjective',
    'Adverb',
    'Verb',
    'Adjective',
    'Noun',
    'Noun',
    'Noun',
    'Verb',
    'Conjunction',
    'Conjunction',
    'Verb',
    'Noun',
    'Verb',
  ],
};
